-- MySQL Script generated by MySQL Workbench
-- Wed Aug 22 01:55:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookazon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookazon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookazon` DEFAULT CHARACTER SET utf8 ;
USE `bookazon` ;

-- -----------------------------------------------------
-- Table `bookazon`.`Authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookazon`.`Authors` ;

CREATE TABLE IF NOT EXISTS `bookazon`.`Authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookazon`.`Books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookazon`.`Books` ;

CREATE TABLE IF NOT EXISTS `bookazon`.`Books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `format` VARCHAR(45) NOT NULL,
  `price` DOUBLE NULL default 0.0,
  `authorId` INT NULL,
  `category` INT NULL,Orders
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookazon`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookazon`.`Categories` ;

CREATE TABLE IF NOT EXISTS `bookazon`.`Categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookazon`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookazon`.`Customers` ;

CREATE TABLE IF NOT EXISTS `bookazon`.`Customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookazon`.`LineItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookazon`.`LineItem` ;

CREATE TABLE IF NOT EXISTS `bookazon`.`LineItem` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bookId` INT NOT NULL,
  `quantity` INT NOT NULL,
  `cost` DOUBLE NULL DEFAULT 0.0,
  `orderId` INT NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) 
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookazon`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookazon`.`Orders` ;

CREATE TABLE IF NOT EXISTS `bookazon`.`Orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `custId` INT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
